.TH WHEREAMI 1
.SH NAME
whereami \- CHANGEME_DESCRIPTION
.\"
.SH SYNOPSIS
.B whereami
[ \fB\-a\fR \fIoption_1_value\fR ]
[ \fB\-\-option1=\fR\fIoption_1_value\fR ]
[ \fB\-b\fR \fIoption_2_value\fR ]
[ \fB\-\-option2=\fR\fIoption_2_value\fR ]
.IR file ...
.\"
.SH DESCRIPTION
.B whereami
Here is a longer description
.\"
.SH OPTIONS
.TP
.BR \-a ", " \-\-option1 =\fIoption_1_value\fR
This describes option1.
The default is something sensible.
.\"
.TP
.BR \-b ", " \-\-option2 =\fIoption_2_value\fR
This describes option2.
The default is something sensible.
.\"
.SH SEE ALSO
.BR manpagename (7)
for more information about something else.
