.TH WHEREAMI 1
.SH NAME
whereami \- CHANGEME_DESCRIPTION
.\"
.SH SYNOPSIS
.B whereami
[ \fB\-a\fR \fIoption_1_value\fR ]
[ \fB\-\-option1=\fR\fIoption_1_value\fR ]
[ \fB\-b\fR \fIoption_2_value\fR ]
[ \fB\-\-option2=\fR\fIoption_2_value\fR ]
.IR file ...
.\"
.SH DESCRIPTION
.B whereami
Here is a longer description
.\"
.SH RETURN VALUE
The
.BR whereami ()
function returns a pointer to ...
.\"
.SH SEE ALSO
.BR manpagename (7)
for more information about something else.
